// attention. In the svg files add  preserveAspectRatio="none" to the svg tag to allow non-uniform scale
export const SymbolsLibrary = [
  {
    label: 'None',
    value: '',
    width: 32,
    height: 32,
    factor: 1,
  },
  {
    label: 'Static Text',
    value: 'text',
    width: 32,
    height: 32,
    factor: 1,
  },
  {
    label: 'Custom Symbol',
    value: 'custom',
    width: 32,
    height: 32,
    factor: 1,
  },
  {
    label: 'Arrow 1',
    value: 'public/plugins/larona-epict-panel/symbols/Arrow1.svg',
    width: 32,
    height: 32,
    factor: 1,
  },
  {
    label: 'Arrow 2',
    value: 'public/plugins/larona-epict-panel/symbols/Arrow2.svg',
    width: 32,
    height: 32,
    factor: 1,
  },
  {
    label: 'Flat Vessel 1',
    value: 'public/plugins/larona-epict-panel/symbols/FlatVessel1.svg',
    width: 16,
    height: 32,
    factor: 8,
  },
  {
    label: 'Line 1',
    value: 'public/plugins/larona-epict-panel/symbols/Line1.svg',
    width: 32,
    height: 32,
    factor: 1,
  },
  {
    label: 'Mixer 1',
    value: 'public/plugins/larona-epict-panel/symbols/Mixer1.svg',
    width: 32,
    height: 32,
    factor: 2,
  },
  {
    label: 'Motor 1',
    value: 'public/plugins/larona-epict-panel/symbols/Motor1.svg',
    width: 32,
    height: 32,
    factor: 2,
  },
  {
    label: 'Pipe 1',
    value: 'public/plugins/larona-epict-panel/symbols/Pipe1.svg',
    width: 32,
    height: 32,
    factor: 1,
  },
  {
    label: 'Pipe 2',
    value: 'public/plugins/larona-epict-panel/symbols/Pipe2.svg',
    width: 32,
    height: 32,
    factor: 2,
  },
  {
    label: 'Pipe 3',
    value: 'public/plugins/larona-epict-panel/symbols/Pipe3.svg',
    width: 32,
    height: 32,
    factor: 2,
  },
  {
    label: 'Pump 1',
    value: 'public/plugins/larona-epict-panel/symbols/Pump1.svg',
    width: 32,
    height: 32,
    factor: 2,
  },
  {
    label: 'Tank 1',
    value: 'public/plugins/larona-epict-panel/symbols/Tank1.svg',
    width: 16,
    height: 32,
    factor: 8,
  },
  {
    label: 'Tank 2',
    value: 'public/plugins/larona-epict-panel/symbols/Tank2.svg',
    width: 16,
    height: 32,
    factor: 8,
  },
  {
    label: 'Tank 3',
    value: 'public/plugins/larona-epict-panel/symbols/Tank3.svg',
    width: 16,
    height: 32,
    factor: 8,
  },
  {
    label: 'Valve 1',
    value: 'public/plugins/larona-epict-panel/symbols/Valve1.svg',
    width: 32,
    height: 16,
    factor: 2,
  },
  {
    label: 'Valve 2',
    value: 'public/plugins/larona-epict-panel/symbols/Valve2.svg',
    width: 32,
    height: 32,
    factor: 2,
  },
];
